version: '2.0'
services:
  springboot:
    build: .
    container_name: springboot
    ports:
      - 8085:8080
    links:
      - dbpostgres
  dbpostgres:
    image: postgres
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nodesdb
